travis:
  secure:
    BINSTAR_TOKEN: cK2hpOsgLpB7k9B94qb5ga0r2E68AyDkNDcREDqTeCQ0VPOb8cSkoqqsTy2xdCJPhn6vCXLQ6xyxpDTKG6WOHLQW1l7tc5XO+Fyyby6n7m9juO8qwCnLoM7l+ikXRLYXEVLTkdwPApEDaTmllcz9r/MZQKeIH1esmEohfEuBorSGxj0TaJvnZ7JA5Y7rYovpSu/l/m3tMqu7a42KWJBXAk0/hyUwA1qfi255S6joeOW9cJdu5nKXObmlbDtPqWtjN7bMKPK/7Nzc3iGTQ2mM7F2U9ZeZRTTyn6nNryneslGFgkZiHCf3K0xlWal2kwEe1X3tLgGJzRewOlb8mqKWuqi2XOEjYwbVPlP/sRIbAfSAp1k1+DLMfPpXaT1pJijHzR2g67YlS8NPLhy811eKzWVcomsQTOIPxk4ZyNCpOgqZVdWg+9Ron3zip1n/4fwS8ykqgSUTexxd/VVWVgzD+8C9TOzOMgNOp0akrD+f3a+BE1dd5P9LJhAWjWQlmRPjUMWo9RN7l3R2tjUDJ8IRixZMGyEKG/iTnnQCPSbuHHK4tIHibC1S6FqS+etYLzIxOULWYr1NOZ7vlx8rahuvmbWVPfGLuwKgxtxfN8ZhDno7sLuhLirobdX4cyZQe92HJX6hhpH+6WdouWu71sBJmcBEdVav0QgDGdFgPzugBoU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
